# Generated by Django 4.1.1 on 2022-09-19 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstcategory',
            options={'verbose_name_plural': 'FirstCategories'},
        ),
        migrations.AlterModelOptions(
            name='secondcategory',
            options={'verbose_name_plural': 'SecondCategories'},
        ),
        migrations.AlterModelOptions(
            name='thirdcategory',
            options={'verbose_name_plural': 'ThirdCategories'},
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='sub_cats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cats', to='categories.firstcategory'),
        ),
        migrations.AlterField(
            model_name='thirdcategory',
            name='sub_categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.secondcategory'),
        ),
    ]
